"""Human-readable Markdown generator."""

from typing import List

from core.models import Equipment, Material, Protocol, SafetyLevel, SafetyNote, Step


class MarkdownGenerator:
    """Generates human-readable Markdown from protocols."""

    @staticmethod
    def generate_protocol_markdown(protocol: Protocol) -> str:
        """
        Generate a human-readable markdown version of the protocol.

        Args:
            protocol: Protocol object

        Returns:
            Markdown-formatted protocol text
        """
        lines = []

        # Header
        lines.append(f"# {protocol.title}")
        lines.append("")
        lines.append(f"**Objective:** {protocol.objective}")
        lines.append(f"**Duration:** {protocol.get_total_duration():.1f} minutes")
        lines.append(f"**Difficulty Level:** {protocol.difficulty_level.value.title()}")
        if protocol.author:
            lines.append(f"**Author:** {protocol.author}")
        if protocol.version:
            lines.append(f"**Version:** {protocol.version}")
        lines.append("")

        # Equipment Required
        if protocol.equipment_required:
            lines.append("## Equipment Required")
            for equipment in protocol.equipment_required:
                qty_str = f" (x{equipment.quantity})" if equipment.quantity > 1 else ""
                lines.append(f"- {equipment.name}{qty_str}")
                if equipment.notes:
                    lines.append(f"  - *{equipment.notes}*")
            lines.append("")

        # Materials Required
        if protocol.materials_required:
            lines.append("## Materials Required")
            for material in protocol.materials_required:
                lines.append(f"- **{material.name}** ({material.amount})")
                if material.type.value != "other":
                    lines.append(f"  - Type: {material.type.value}")
                if material.concentration:
                    lines.append(f"  - Concentration: {material.concentration}")
                if material.storage_conditions:
                    lines.append(f"  - Storage: {material.storage_conditions}")
                if material.notes:
                    lines.append(f"  - *{material.notes}*")
            lines.append("")

        # Safety Considerations
        if protocol.safety_notes:
            lines.append("## Safety Considerations")
            for note in protocol.safety_notes:
                level_icon = MarkdownGenerator._get_safety_icon(note.level)
                lines.append(
                    f"- {level_icon} **{note.level.value.upper()}**: {note.description}"
                )
                if note.ppe_required:
                    lines.append(
                        f"  - **PPE Required:** {', '.join(note.ppe_required)}"
                    )
                if note.hazards:
                    lines.append(f"  - **Hazards:** {', '.join(note.hazards)}")
            lines.append("")

        # Step-by-Step Protocol
        lines.append("## Step-by-Step Protocol")
        lines.append("")

        for step in protocol.steps:
            lines.append(f"### Step {step.step_number}: {step.description}")
            lines.append("")

            # Duration
            if step.duration_minutes > 0:
                lines.append(f"**Duration:** {step.duration_minutes:.1f} minutes")
                lines.append("")

            # Equipment used in this step
            if step.equipment:
                lines.append(f"**Equipment:** {', '.join(step.equipment)}")
                lines.append("")

            # Materials used in this step
            if step.materials:
                lines.append(f"**Materials:** {', '.join(step.materials)}")
                lines.append("")

            # Critical parameters
            if step.critical_parameters:
                lines.append("**Critical Parameters:**")
                for param, value in step.critical_parameters.items():
                    lines.append(f"- {param.title()}: {value}")
                lines.append("")

            # Notes
            if step.notes:
                lines.append(f"**Notes:** {step.notes}")
                lines.append("")

        # References
        if protocol.references:
            lines.append("## References")
            for ref in protocol.references:
                lines.append(f"- {ref}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Lab-Rador Protocol Automator*")
        lines.append(f"*Created: {protocol.created_at.strftime('%Y-%m-%d %H:%M:%S')}*")

        return "\n".join(lines)

    @staticmethod
    def _get_safety_icon(level: SafetyLevel) -> str:
        """Get appropriate icon for safety level."""
        icons = {
            SafetyLevel.LOW: "ℹ️",
            SafetyLevel.MEDIUM: "⚠️",
            SafetyLevel.HIGH: "🚨",
            SafetyLevel.CRITICAL: "☠️",
        }
        return icons.get(level, "⚠️")

    @staticmethod
    def generate_protocol_summary(protocol: Protocol) -> str:
        """
        Generate a concise summary of the protocol.

        Args:
            protocol: Protocol object

        Returns:
            Markdown-formatted summary
        """
        lines = []
        lines.append(f"## {protocol.title}")
        lines.append("")
        lines.append(f"**Duration:** {protocol.get_total_duration():.1f} minutes")
        lines.append(f"**Steps:** {len(protocol.steps)}")
        lines.append(f"**Equipment:** {len(protocol.equipment_required)} items")
        lines.append(f"**Materials:** {len(protocol.materials_required)} items")
        lines.append(f"**Difficulty:** {protocol.difficulty_level.value.title()}")

        if protocol.safety_notes:
            high_risk = [
                note
                for note in protocol.safety_notes
                if note.level in [SafetyLevel.HIGH, SafetyLevel.CRITICAL]
            ]
            if high_risk:
                lines.append(f"**⚠️ High Risk Notes:** {len(high_risk)}")

        return "\n".join(lines)
